name: Java CI

on:
  schedule:
    - cron: '*/1 * * * *'
  push:
    branches:
      - master
    paths:
      - 'summaries/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean build
